# Generated by Django 3.1.4 on 2020-12-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='shortened_url',
            field=models.URLField(unique=True),
        ),
    ]
